# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('posts', '0003_auto_20171127_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='categories.Category'),
        ),
    ]
